feat: implement tabs component
kata-ai/aksara-ui pull request #326
Opened 2021-03-01 07:52 UTC by rohmad-st

Closed  #266 

- Implement tabs component
- also export * from UnstyledButton

2021-03-01 09:28 UTC, resir014 requested changes
Ada beberapa comment ya @rohmad-st, silakan direview.

2021-03-01 09:28 UTC, resir014 commented on packages/aksara-ui-core/src/components/tabs/components/Tabs.stories.tsx
> +};
```suggestion
```

Karena setting Size ini sudah masuk ke storybook knobs, story yang ini dihapus aja.

2021-03-01 09:28 UTC, resir014 commented on packages/aksara-ui-core/src/components/tabs/styles.ts
> +  }
Lebih baik ini semua dipisah ke styled-component sendiri aja ya.

2021-03-01 09:28 UTC, resir014 commented on packages/aksara-ui-core/src/components/tabs/styles.ts
> +  display: block;
Use `<Box display="block" ...>`

2021-03-02 03:25 UTC, rohmad-st commented
Okay @resir014 sudah ku follow up yaa terkait beberapa feedback nya. Thanks.
Silakan di review lagi

2021-03-02 05:42 UTC, resir014 approved these changes

2021-03-02 05:43 UTC, merged