WIP: feat: implement pill component
kata-ai/aksara-ui pull request #341
Opened 2021-03-08 04:37 UTC by rohmad-st

Related #264

2021-03-18 04:13 UTC, resir014 approved these changes

2021-03-18 06:01 UTC, resir014 requested changes
@rohmad-st Ada satu review item aja ya, please check.

2021-03-18 06:01 UTC, resir014 commented on packages/aksara-ui-core/src/theme/componentStyles/pill.ts
> +        borderStyle: 'solid',
Untuk `borderWidth` dan `borderStyle` ini lebih baik ditaruh di `baseStyle`, supaya gak ada perbedaan width/height pada saat beda variant:

![JLIxugWBs8](https://user-images.githubusercontent.com/5663877/111580366-f60b5680-87e9-11eb-97fa-97e2c27e8cf8.gif)

Untuk yang gak ada bordernya `borderColor` diganti jadi `transparent`.

2021-03-19 07:04 UTC, rohmad-st commented on packages/aksara-ui-core/src/theme/componentStyles/pill.ts
> +        borderStyle: 'solid',
Okay bro @resir014 sudah ku betulkan yaa

2021-03-19 08:54 UTC, resir014 approved these changes

2021-03-19 08:54 UTC, merged